// <auto-generated />
using System;
using Media.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Media.Migrations
{
    [DbContext(typeof(MediaContext))]
    [Migration("20250629072050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Media.Models.Episodes", b =>
                {
                    b.Property<int>("epId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("epId"));

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("episodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("episodeNumber")
                        .HasColumnType("int");

                    b.Property<int>("mediaId")
                        .HasColumnType("int");

                    b.Property<string>("overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stillPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("epId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("mediaId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Media.Models.Files", b =>
                {
                    b.Property<int>("fid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fid"));

                    b.Property<string>("fileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mediaId")
                        .HasColumnType("int");

                    b.Property<int>("playhistory")
                        .HasColumnType("int");

                    b.HasKey("fid");

                    b.HasIndex("mediaId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Media.Models.Genre", b =>
                {
                    b.Property<int>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gid"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genreId")
                        .HasColumnType("int");

                    b.HasKey("Gid");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Media.Models.History", b =>
                {
                    b.Property<int>("historyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("historyId"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<int>("episodeNumber")
                        .HasColumnType("int");

                    b.Property<bool>("isFinished")
                        .HasColumnType("bit");

                    b.Property<int>("mediaId")
                        .HasColumnType("int");

                    b.Property<int>("position")
                        .HasColumnType("int");

                    b.Property<int>("seasonNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("watchedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("historyId");

                    b.HasIndex("UserId");

                    b.HasIndex("mediaId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("Media.Models.Images", b =>
                {
                    b.Property<int>("imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("imageId"));

                    b.Property<int?>("episodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("height")
                        .HasColumnType("int");

                    b.Property<string>("imageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mediaId")
                        .HasColumnType("int");

                    b.Property<int?>("seasonNumber")
                        .HasColumnType("int");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("width")
                        .HasColumnType("int");

                    b.HasKey("imageId");

                    b.HasIndex("mediaId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Media.Models.MediaCast", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("MediaId");

                    b.ToTable("MediaCasts");
                });

            modelBuilder.Entity("Media.Models.MediaGenres", b =>
                {
                    b.Property<int>("mediaGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mediaGenreId"));

                    b.Property<int>("genreId")
                        .HasColumnType("int");

                    b.Property<int>("mediaId")
                        .HasColumnType("int");

                    b.HasKey("mediaGenreId");

                    b.HasIndex("genreId");

                    b.HasIndex("mediaId");

                    b.ToTable("MediaGenres");
                });

            modelBuilder.Entity("Media.Models.MediaItem", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("BackdropPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TMDbId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediaId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("Media.Models.MovieDetail", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediaId");

                    b.ToTable("MovieDetails");
                });

            modelBuilder.Entity("Media.Models.Playlist", b =>
                {
                    b.Property<int>("playlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("playlistId"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isSystem")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("playlistId");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Media.Models.PlaylistItems", b =>
                {
                    b.Property<int>("playlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("playlistItemId"));

                    b.Property<DateTime>("addedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("mediaId")
                        .HasColumnType("int");

                    b.Property<int>("playlistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("releaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("playlistItemId");

                    b.HasIndex("mediaId");

                    b.HasIndex("playlistId");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("Media.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.HasKey("SeasonId");

                    b.HasIndex("MediaId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Media.Models.SeriesDetail", b =>
                {
                    b.Property<int>("mediaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("firstAirDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("numberOfEpisodes")
                        .HasColumnType("int");

                    b.Property<int>("numberOfSeasons")
                        .HasColumnType("int");

                    b.HasKey("mediaId");

                    b.ToTable("SeriesDetail");
                });

            modelBuilder.Entity("Media.Models.Token", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Media.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Media.Models.WatchProgress", b =>
                {
                    b.Property<int>("watchProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("watchProgressId"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("episodeNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastWatched")
                        .HasColumnType("datetime2");

                    b.Property<int>("mediaId")
                        .HasColumnType("int");

                    b.Property<int>("position")
                        .HasColumnType("int");

                    b.Property<int>("seasonNumber")
                        .HasColumnType("int");

                    b.HasKey("watchProgressId");

                    b.HasIndex("UserId");

                    b.HasIndex("mediaId");

                    b.ToTable("WatchProgress");
                });

            modelBuilder.Entity("Media.Models.Episodes", b =>
                {
                    b.HasOne("Media.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany("Episodes")
                        .HasForeignKey("mediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Media.Models.Files", b =>
                {
                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("mediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Media.Models.History", b =>
                {
                    b.HasOne("Media.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("mediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Media.Models.Images", b =>
                {
                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("mediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Media.Models.MediaCast", b =>
                {
                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Media.Models.MediaGenres", b =>
                {
                    b.HasOne("Media.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("genreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("mediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Media.Models.MovieDetail", b =>
                {
                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Media.Models.Playlist", b =>
                {
                    b.HasOne("Media.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Media.Models.PlaylistItems", b =>
                {
                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("mediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Media.Models.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("playlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Media.Models.Season", b =>
                {
                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany("Seasons")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Media.Models.SeriesDetail", b =>
                {
                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("mediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Media.Models.Token", b =>
                {
                    b.HasOne("Media.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Media.Models.WatchProgress", b =>
                {
                    b.HasOne("Media.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Media.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("mediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Media.Models.MediaItem", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Media.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
